spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ttcitisDB
    username: citis
    password: citis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

tt:
  security:
    publicURLs: /login
    adminPassword: deqqewt31sAQfg
    jwt:
      expirationMs: 28800000 # 8 hours
      secret: X6*YW5c3ZX3GQ$VjQM9R$dTtwhhErw$k
debug: true
