spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ttcitisDB
    username: citis
    password: citis
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

tt:
  security:
    publicURLs: /login
    adminPassword: deqqewt31sAQfg
    jwt:
      expirationMs: 28800000 # 8 hours
      secret: X6*YW5c3ZX3GQ$VjQM9R$dTtwhhErw$k
debug: true
